# Save and Load Model

In [1]:
import keras
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense
from keras.optimizers import Adam

e:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
model = keras.models.Sequential([
    Dense(16, input_shape=(1,), activation='relu'),
    Dense(32, activation='relu'),
    Dense(2, activation='softmax')
])

In [3]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_2 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.compile(Adam(lr=.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

## Save both model architecture and weights

In [5]:
from keras.models import load_model

In [6]:
model.save('test_save_model.h5')

In [7]:
new_model = load_model('test_save_model.h5')

In [8]:
new_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_2 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [9]:
new_model.get_weights()

[array([[-0.22471803, -0.17725345,  0.57099545, -0.15750816,  0.4910965 ,
          0.28733587, -0.48564056, -0.5763594 ,  0.14153963, -0.27892318,
          0.4949416 ,  0.21909344, -0.27420822, -0.50546247,  0.10268843,
          0.29593492]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=float32),
 array([[ 0.25249866, -0.32634118,  0.02234542, -0.25476438,  0.1823481 ,
         -0.13048698, -0.09746224, -0.06950983,  0.03692603,  0.05901149,
         -0.13105369,  0.20376763,  0.00760818, -0.02380016,  0.16543463,
         -0.19219898,  0.12731475,  0.282424  , -0.07913104,  0.05770713,
         -0.05720028, -0.06774381,  0.11680037,  0.3151581 , -0.2707168 ,
         -0.33329046,  0.16198179, -0.01646128, -0.08630133, -0.17908837,
          0.04819939, -0.26208967],
        [ 0.14596719,  0.0312303 ,  0.05225173, -0.29621607,  0.20018682,
          0.04042843,  0.31604537, -0.12670977, -0.28957406, -0.13301013,
          0.06

In [10]:
new_model.optimizer

## Save model architecture only

### 1. to json

In [11]:
from keras.models import model_from_json

In [12]:
json_string = model.to_json()

In [13]:
json_string

'{"class_name": "Sequential", "config": [{"class_name": "Dense", "config": {"name": "dense_1", "trainable": true, "batch_input_shape": [null, 1], "dtype": "float32", "units": 16, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"scale": 1.0, "mode": "fan_avg", "distribution": "uniform", "seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Dense", "config": {"name": "dense_2", "trainable": true, "units": 32, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"scale": 1.0, "mode": "fan_avg", "distribution": "uniform", "seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "b

In [14]:
model_architecture_json = model_from_json(json_string)

In [15]:
model_architecture_json.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_2 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


### 2. to yaml

In [16]:
from keras.models import model_from_yaml

In [17]:
yaml_string = model.to_yaml()

In [18]:
yaml_string

'backend: tensorflow\nclass_name: Sequential\nconfig:\n- class_name: Dense\n  config:\n    activation: relu\n    activity_regularizer: null\n    batch_input_shape: !!python/tuple [null, 1]\n    bias_constraint: null\n    bias_initializer:\n      class_name: Zeros\n      config: {}\n    bias_regularizer: null\n    dtype: float32\n    kernel_constraint: null\n    kernel_initializer:\n      class_name: VarianceScaling\n      config: {distribution: uniform, mode: fan_avg, scale: 1.0, seed: null}\n    kernel_regularizer: null\n    name: dense_1\n    trainable: true\n    units: 16\n    use_bias: true\n- class_name: Dense\n  config:\n    activation: relu\n    activity_regularizer: null\n    bias_constraint: null\n    bias_initializer:\n      class_name: Zeros\n      config: {}\n    bias_regularizer: null\n    kernel_constraint: null\n    kernel_initializer:\n      class_name: VarianceScaling\n      config: {distribution: uniform, mode: fan_avg, scale: 1.0, seed: null}\n    kernel_regularizer:

In [19]:
model_architecture_yaml = model_from_yaml(yaml_string)

In [20]:
model_architecture_yaml.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_2 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


## Save model weights only

In [21]:
model.save_weights('save_weights_only.h5')

In [22]:
new_model = Sequential([
    Dense(16, input_shape=(1,), activation='relu'),
    Dense(32, activation='relu'),
    Dense(2, activation='softmax')
])

In [23]:
new_model.load_weights('save_weights_only.h5')

In [24]:
new_model.get_weights()

[array([[-0.22471803, -0.17725345,  0.57099545, -0.15750816,  0.4910965 ,
          0.28733587, -0.48564056, -0.5763594 ,  0.14153963, -0.27892318,
          0.4949416 ,  0.21909344, -0.27420822, -0.50546247,  0.10268843,
          0.29593492]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=float32),
 array([[ 0.25249866, -0.32634118,  0.02234542, -0.25476438,  0.1823481 ,
         -0.13048698, -0.09746224, -0.06950983,  0.03692603,  0.05901149,
         -0.13105369,  0.20376763,  0.00760818, -0.02380016,  0.16543463,
         -0.19219898,  0.12731475,  0.282424  , -0.07913104,  0.05770713,
         -0.05720028, -0.06774381,  0.11680037,  0.3151581 , -0.2707168 ,
         -0.33329046,  0.16198179, -0.01646128, -0.08630133, -0.17908837,
          0.04819939, -0.26208967],
        [ 0.14596719,  0.0312303 ,  0.05225173, -0.29621607,  0.20018682,
          0.04042843,  0.31604537, -0.12670977, -0.28957406, -0.13301013,
          0.06